/*
 * wordpiece-lab.js — the shared, React-free half of the four widgets in
 * wordpiece-token-search.mdx: WordpieceSplit, ThreeChannels, PieceDerivation
 * and WeightHandoff.
 *
 * It holds three things:
 *   1. a real greedy WordPiece tokenizer, run against the actual
 *      bert-base-uncased vocabulary fetched from /static/data at first use,
 *   2. the fallback splits those widgets show if that fetch fails, so the post
 *      still reads correctly with a dead network,
 *   3. the toy corpus and stem families the mechanism widgets walk through,
 *      plus labChrome(), which composes the widget palette out of
 *      chartChrome() and vizPalette() rather than inlining a fifth copy of the
 *      neutrals (see chart-style.md).
 *
 * Every split and every stem below was generated by the real tools:
 * transformers' bert-base-uncased tokenizer and snowballstemmer's English
 * stemmer, the same stemmer the benchmark runs use. See
 * scripts/wordpiece-lab-data.py.
 */

import { chartChrome, vizPalette } from './viz-palette'

export const VOCAB_URL = '/static/data/bert-base-uncased-vocab.txt'
export const VOCAB_SIZE = 30522

// ── the tokenizer ──────────────────────────────────────────────────────────

// BERT's basic tokenizer, minus accent stripping: lowercase, split on
// whitespace, then cut punctuation off as its own token.
export function basicTokenize(text) {
  const out = []
  for (const chunk of String(text).toLowerCase().split(/\s+/)) {
    if (!chunk) continue
    let buf = ''
    for (const ch of chunk) {
      if (/[a-z0-9]/.test(ch)) {
        buf += ch
      } else {
        if (buf) out.push(buf)
        buf = ''
        out.push(ch)
      }
    }
    if (buf) out.push(buf)
  }
  return out
}

// Greedy longest-match-first, the WordPiece algorithm itself. Returns [UNK]
// for a word no prefix of which is in the vocabulary.
export function wordpiece(word, vocab) {
  if (!vocab) return null
  if (word.length > 100) return ['[UNK]']
  const pieces = []
  let start = 0
  while (start < word.length) {
    let end = word.length
    let found = null
    while (start < end) {
      const sub = (start === 0 ? '' : '##') + word.slice(start, end)
      if (vocab.has(sub)) {
        found = sub
        break
      }
      end -= 1
    }
    if (found === null) return ['[UNK]']
    pieces.push(found)
    start = end
  }
  return pieces
}

let vocabPromise = null

// One fetch per page, shared by every widget that needs it.
export function loadVocab() {
  if (typeof window === 'undefined') return Promise.resolve(null)
  if (!vocabPromise) {
    vocabPromise = fetch(VOCAB_URL)
      .then((r) => {
        if (!r.ok) throw new Error(`vocab ${r.status}`)
        return r.text()
      })
      .then((t) => new Set(t.split('\n').filter(Boolean)))
      .catch(() => null)
  }
  return vocabPromise
}

// Splits verified against the real tokenizer, used as the preset row and as
// the fallback when the vocabulary cannot be fetched.
export const KNOWN_SPLITS = {
  tokenization: ['token', '##ization'],
  tokenizer: ['token', '##izer'],
  tokenizers: ['token', '##izer', '##s'],
  tokens: ['token', '##s'],
  token: ['token'],
  wordpiece: ['word', '##piece'],
  retrieval: ['retrieval'],
  storage: ['storage'],
  racing: ['racing'],
  obsesses: ['ob', '##ses', '##ses'],
  belvidere: ['bel', '##vid', '##ere'],
  antinutrients: ['anti', '##nut', '##rien', '##ts'],
  methods: ['methods'],
  splits: ['splits'],
  budgets: ['budgets'],
  index: ['index'],
  survey: ['survey'],
  costs: ['costs'],
  text: ['text'],
  embedding: ['em', '##bed', '##ding'],
}

// Real vocabulary entries that none of the toy documents contain, used to show
// what having no posting looks like.
export const ABSENT_PIECES = ['##izer', '##ogy', '##bed']

export const SPLIT_PRESETS = [
  'tokenization',
  'tokenizers',
  'obsesses',
  'belvidere',
  'a survey of tokenization methods',
]

// Tokenize a phrase, preferring the real vocabulary and falling back to the
// table above so the widget still answers for its own presets offline.
export function splitPhrase(text, vocab) {
  return basicTokenize(text).map((w) => ({
    word: w,
    pieces: wordpiece(w, vocab) || KNOWN_SPLITS[w] || null,
  }))
}

// ── the toy corpus the mechanism widgets walk through ──────────────────────

// Four short documents, chosen so the three channels disagree: d1 holds the
// query word itself, d2 and d3 hold other members of its stem family, d4 holds
// neither. Stems are snowballstemmer English: tokenization, tokenizer, tokens
// and token all stem to `token`, while storage stems to `storag` and joins
// nothing.
export const DOCS = [
  { id: 'd1', text: 'a survey of tokenization methods', words: { tokenization: 2, methods: 1 } },
  { id: 'd2', text: 'the tokenizer splits text', words: { tokenizer: 1, splits: 1 } },
  { id: 'd3', text: 'token budgets, and token counts', words: { token: 3, budgets: 1 } },
  { id: 'd4', text: 'storage costs of an index', words: { storage: 1, index: 1 } },
]

export const STEMS = {
  tokenization: 'token',
  tokenizer: 'token',
  tokenizers: 'token',
  tokens: 'token',
  token: 'token',
  storage: 'storag',
  store: 'store',
  racing: 'race',
  races: 'race',
  racer: 'racer',
  methods: 'method',
  splits: 'split',
  budgets: 'budget',
  index: 'index',
}

export const QUERIES = ['tokenization', 'token', 'storage']

// The word postings the derivation widget reads from, and the pieces each word
// contains. count is how many times a piece occurs inside that one word, which
// is why `obsesses` carries ##ses twice.
export const DERIVE_WORDS = [
  { word: 'tokenization', pieces: ['token', '##ization'], postings: { d1: 2, d3: 1 } },
  { word: 'tokenizer', pieces: ['token', '##izer'], postings: { d2: 1 } },
  { word: 'tokens', pieces: ['token', '##s'], postings: { d1: 1 } },
  { word: 'token', pieces: ['token'], postings: { d3: 3 } },
]

export const DERIVE_DOCS = ['d1', 'd2', 'd3']

// tf_p(d) = sum over words v containing p of count_p(v) * tf_v(d)
export function derivePieces(words, docs) {
  const acc = {}
  for (const w of words) {
    for (const p of new Set(w.pieces)) {
      const count = w.pieces.filter((x) => x === p).length
      acc[p] = acc[p] || {}
      for (const d of docs) acc[p][d] = (acc[p][d] || 0) + count * (w.postings[d] || 0)
    }
  }
  return acc
}

// ── the palette every widget draws with ────────────────────────────────────

export function labChrome(dark) {
  const chrome = chartChrome(dark)
  const vp = vizPalette(dark)
  return {
    ...chrome,
    dark,
    // identity slots, assigned in order: piece, exact word, stem family.
    channel: [vp.series0, vp.series1, vp.series2],
    off: vp.muted,
    // POLARITY, and the only place these widgets spend it: a posting the
    // derivation invents is a failure, not another category.
    bad: vp.bad,
    fill: dark ? 'rgba(255,255,255,0.04)' : '#f2f4f2',
    lane: dark ? 'rgba(255,255,255,0.015)' : '#fbfcfb',
  }
}

export const MONO = 'var(--font-mono, ui-monospace, SFMono-Regular, Menlo, monospace)'

// A chip is the one repeated shape across all four widgets: a bordered mono
// box holding a piece, a word or a document id.
export function chipStyle(c, { on = true, tint, strike = false } = {}) {
  return {
    display: 'inline-flex',
    alignItems: 'baseline',
    gap: 5,
    padding: '4px 9px',
    borderRadius: 2,
    fontSize: 12.5,
    fontFamily: MONO,
    whiteSpace: 'nowrap',
    background: on ? (tint ? hexFade(tint, c.dark ? 0.16 : 0.1) : c.fill) : 'transparent',
    color: on ? tint || c.ink : c.muted,
    border: `1px solid ${on ? tint || c.axis : c.border}`,
    textDecoration: strike ? 'line-through' : 'none',
    opacity: on ? 1 : 0.6,
  }
}

// A translucent wash of a role colour, so a tinted chip stays legible in both
// themes without a second hardcoded value per role.
export function hexFade(hex, alpha) {
  const h = hex.replace('#', '')
  const n = parseInt(
    h.length === 3
      ? h
          .split('')
          .map((x) => x + x)
          .join('')
      : h,
    16
  )
  return `rgba(${(n >> 16) & 255}, ${(n >> 8) & 255}, ${n & 255}, ${alpha})`
}

export const LABEL = {
  fontSize: 10,
  fontWeight: 700,
  letterSpacing: '0.07em',
  textTransform: 'uppercase',
  fontFamily: MONO,
}

export function segButton(c, on) {
  return {
    appearance: 'none',
    cursor: 'pointer',
    fontSize: 12,
    lineHeight: 1,
    padding: '6px 12px',
    border: `1px solid ${on ? c.accent : c.border}`,
    background: on ? c.accent : 'transparent',
    color: on ? c.accentInk : c.muted,
    fontFamily: MONO,
    fontWeight: on ? 600 : 400,
    position: 'relative',
    zIndex: on ? 1 : 0,
    borderRadius: 2,
  }
}

export function cardStyle(c) {
  return {
    background: c.card,
    border: `1px solid ${c.border}`,
    borderRadius: 2,
    padding: 'clamp(12px, 3vw, 16px)',
    margin: '1.5rem 0',
    color: c.ink,
    fontFamily: MONO,
  }
}
